# Permalinks
permalink:           pretty

# Setup
title:               James Mizen
tagline:             Music et cetera
url:                 http://miiizen.github.io
paginate:            5
paginate_path:       "/blog/page:num/"
baseurl:             ""

google_verify: btpsS4yph70BxXmVwumLM2YpbljudFK8cLyGKOemNGw

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              James Mizen
  url:               https://github.com/miiizen

collections:
  projects:
    output: true
    permalink: /:collection/:title/
  music:
    output: true
    permalink: /:collection/:title/


# deployment
host: 0.0.0.0
port: 4000

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap
